---
- hosts: all
  sudo: true
  roles:
    - essential
    - supervisor
    - role: bennojoy.nginx
      nginx_sites: none
    - postgresql

- hosts: graphiteservers
  sudo: true
  vars:
    graphite:
      timezone: Etc/UTC
      server: graphite.local
      secret_key: '7/C1yN7PINoicYzKyx2mR2TdMLJdDXTi18rbHGFiX78='
      db:
        name: graphite
        user: graphite
        password: graphite
    carbon:
      ssl: no
  roles:
    - apache2
    - carbon
    - graphite
    - statsd

- hosts: sentryservers
  sudo: true
  vars:
    sentry:
      server: sentry.local
      url: http://sentry.local
      secret_key: 'DR03hvVY8ouSfw38hkUp24C/5bZj6vIi3cpmwqCFRkw='
      db:
        name: sentry
        user: sentry
        password: sentry
    superuser_sentry:
      username: admin
      email: admin@example.com
      password: admin
      organization: default
      team: default
      project: default
      platform: python
  roles:
    - role: DavidWittman.redis
      redis_bind: 127.0.0.1
    - python
    - sentry
