---
- hosts: all
  sudo: True
  vars:
    apache2:
      port: 8080
    graphite:
      timezone: Etc/UTC
      server: graphite.local
      secret_key: '7/C1yN7PINoicYzKyx2mR2TdMLJdDXTi18rbHGFiX78='
      db:
        name: graphite
        user: graphite
        password: graphite
    carbon:
      ssl: no
    sentry:
      server: sentry.local
      url: http://sentry.local
      secret_key: 'DR03hvVY8ouSfw38hkUp24C/5bZj6vIi3cpmwqCFRkw='
      db:
        name: sentry
        user: sentry
        password: sentry
    superuser_sentry:
      username: admin
      email: admin@example.com
      password: admin
      organization: default
      team: default
      project: default
      platform: python
  roles:
    - common
    - supervisor
    - apache2
    - role: bennojoy.nginx
      nginx_sites: none
    - postgresql
    - carbon
    - graphite
#    - python
#    - nodejs
#    - npm
#    - statsd
#    - sentry

