- name: install
  apt: "name={{ item }} state=installed"
  with_items: [apache2, libapache2-mod-wsgi]

- name: copy configuration
  template: src=ports.conf.j2
            dest=/etc/apache2/ports.conf
            mode=0644

- name: disable the default host file
  command: sudo a2dissite 000-default

- name: start service & enable on boot
  service: name=apache2 state=started enabled=yes
