- name: install statsd
  npm: name=statsd global=yes

- name: configure statsd
  template: src=config.js.j2 dest=/opt/statsd/config.js

- name: copy supervisor configuration for statsd
  template: src=supervisor-statsd.conf.j2 dest=/etc/supervisor/conf.d/statsd.conf
  notify:
    - reload supervisor