- name: copy nginx configuration
  template: src=nginx-sentry.conf.j2
            dest=/etc/nginx/sites-available/sentry.conf
            owner={{ nginx_user }}
            group={{ nginx_group }}

- name: link nginx configuration
  file: src=/etc/nginx/sites-available/sentry.conf
        dest=/etc/nginx/sites-enabled/sentry.conf
        state=link
        owner={{ nginx_user }}
        group={{ nginx_group }}
  notify:
    - restart nginx
