- name: install required packages for graphite
  apt: pkg={{ item }} state=latest
  with_items:
    - memcached
    - libcairo2-dev
    - libffi-dev # for cairocffi

- name: ensure graphite directory exists
  file:
    path: /opt/graphite/
    state: directory

- name: install graphite python deps and create virtualenv if needed
  pip:
    name: {{ item }}
    virtualenv: "{{ venv }}"
    virtualenv_site_packages: no
  with_items:
    - psycopg2
    - django<1.7
    - django-tagging
    - python-memcached
    - pytz
    - pyparsing
    - gunicorn
    - twisted
    - cairocffi # Drop-in replacement for py2cairo. Can be installed inside virtualenv. See http://stackoverflow.com/questions/11491268/install-pycairo-in-virtualenv

- include: whisper.yml
- include: carbon.yml

- name: install
  pip: name=graphite-web

- name: graphite conf
  template: src=local_settings.py.j2
            dest=/opt/graphite/webapp/graphite/local_settings.py
            mode=0644

- name: syncdb for graphite
  shell: export PYTHONPATH=/opt/graphite/webapp/; /opt/graphite/bin/python /opt/graphite/bin/django-admin.py syncdb --noinput --settings=graphite.settings

- name: graphite log folder
  file: path=/opt/graphite/storage/log/webapp
        state=directory

- include: supervisor.yml
- include: nginx.yml
