- name: postgresql | setup database
  sudo_user: postgres
  postgresql_db:
    db: "{{ graphite.db.name }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present

- name: postgresql | grant access to database
  sudo_user: postgres
  postgresql_user:
    db: "{{ graphite.db.name }}"
    user: "{{ graphite.db.user }}"
    password: "{{ graphite.db.password }}"
    role_attr_flags: "CREATEDB,SUPERUSER"
    state: present
